### ISSUE TITLE
xyz_crop.pkl文件

### ISSUE THREAD

**Issue by YINWIZHANG** [THU-DA-6D-Pose-Group/GDR-Net#10]
在训练的时候找不到xyz_crop文件，请问可以在哪里找到？

**Comment by wangg12** [comment]
refer to: https://github.com/THU-DA-6D-Pose-Group/GDR-Net/issues/5

**Comment by YINWIZHANG** [comment]
You said "These are the labels for M_XYZ, i.e., the 3D object coordinates projected in the image space.
For now you need to manually generate them by:

either rendering the coordinates using an OpenGL renderer
or backprojecting the rendered depths.
Note that you need to also crop the patches by the 2D bounding box."

This still confuses me.  When you say "rendering the coordinates using an OpenGL renderer", what is the input?

**Comment by YINWIZHANG** [comment]
Maybe you can just share the pkl folder so that we can have a better idea about that.

**Comment by wangg12** [comment]
> You said "These are the labels for M_XYZ, i.e., the 3D object coordinates projected in the image space.
> For now you need to manually generate them by:
> 
> either rendering the coordinates using an OpenGL renderer
> or backprojecting the rendered depths.
> Note that you need to also crop the patches by the 2D bounding box."
> 
> This still confuses me. When you say "rendering the coordinates using an OpenGL renderer", what is the input?

This is an example: https://github.com/kirumang/Pix2Pose/blob/master/tools/2_1_ply_file_to_3d_coord_model.py. However, we don't need to save the xyz colored models, colors can be assigned by xyz online very easily.

**Comment by YINWIZHANG** [comment]
If I understand it correctly, this repo only includes the GDR Net, but does not include the segmentation head, is that correct? Does it mean you are assuming the segmentation is perfect?

**Comment by wangg12** [comment]
> If I understand it correctly, this repo only includes the GDR Net, but does not include the segmentation head, is that correct? Does it mean you are assuming the segmentation is perfect?

No.

**Comment by YINWIZHANG** [comment]
> > If I understand it correctly, this repo only includes the GDR Net, but does not include the segmentation head, is that correct? Does it mean you are assuming the segmentation is perfect?
> 
> No.

So I need to find a way to segment the data as you mentioned in the paper, then feed it to your model, right?

**Comment by wangg12** [comment]
> > > If I understand it correctly, this repo only includes the GDR Net, but does not include the segmentation head, is that correct? Does it mean you are assuming the segmentation is perfect?
> > 
> > 
> > No.
> 
> So I need to find a way to segment the data as you mentioned in the paper, then feed it to your model, right?

By "No", I mean your understanding is not correct.

**Comment by YINWIZHANG** [comment]
> > > > If I understand it correctly, this repo only includes the GDR Net, but does not include the segmentation head, is that correct? Does it mean you are assuming the segmentation is perfect?
> > > 
> > > 
> > > No.
> > 
> > 
> > So I need to find a way to segment the data as you mentioned in the paper, then feed it to your model, right?
> 
> By "No", I mean your understanding is not correct.

Thanks for your patience, I think I may miss something. In the paper, "As shown in Fig. 2, we feed the GDR-Net with a zoomed-in RoI of size 256 × 256", would you like to point out what is the code to get a zoomed-in ROI given a raw image?

**Comment by wangg12** [comment]
https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/core/gdrn_modeling/data_loader.py#L427

**Comment by YINWIZHANG** [comment]
> https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/core/gdrn_modeling/data_loader.py#L427

Thank you, this would be really helpful!
