### ISSUE TITLE
使用当前实验设置可以直接在BOP上面测试BOP指标吗

### ISSUE THREAD

**Issue by mate-huaboy** [THU-DA-6D-Pose-Group/GDR-Net#100]
王博您好，您的工作对我启发很大，因此我有一些工作是基于您的工作在做的。现在我想要测试我修改后的工作的BOP指标（vsd，mssd，mspd）的情况，我在配置文件中指明了相应测试指标，但是我发现测试代码并不能正常运行，主要是vsd的渲染相关的程序会报错。我主要有以下两个问题：
1）现在的代码可以方便的进行BOP测试吗，比如修改配置文件中的测试指标为vsd，mssd，mspd（VAL字典），程序是否可以方便的运行呢，我不太清楚需要修改相关代码还是可以直接使用。
2）现在的实验设置（论文中提到的对LM，LM-O上的设置）是否可以直接进行BOP的评估呢。也就是说当前实验设置是否和BOP指出的实验设置一致呢，还是需要重新设置相关实验重新开始设置呢。
由于论文rebuttal时间有限，有限问题我不得不直接请教您而可能没有做充分的调查（在issues里面没能找到），希望能得到您的恢复。感谢。

**Comment by wangg12** [comment]
vsd的渲染问题应该是你bop_renderer没安装好或者配置不对。

BOP的训练、测试集和通常意义的LM, LM-O是不一样的，你需要按照BOP的设定去训练，测试。

BOP相关的实验config可以参考：https://github.com/shanice-l/gdrnpp_bop2022
