### ISSUE TITLE
About the details about MSRA

### ISSUE THREAD

**Issue by igodrr** [THU-DA-6D-Pose-Group/GDR-Net#101]
Hello author, 
  I'm not quite clear about how to obtain the GT Surface Region Attention Maps (MSRA) supervision. Could you please explain it in detail?Is the number of regions is 64 means the The number of points sampled by the farthest point sampling is 64 and the dimension of the output feature map is H*W*64? The number of channels is  4mn+m+1 in the (EPOS: Estimating 6D Pose of Objects with Symmetries), I would like to know if there is any difference.
  Looking forward to your reply, thank you very much!

**Comment by wangg12** [comment]
gt region id is obtained by assigning a 3D point to its closest FPS point id.

**Comment by igodrr** [comment]
Thanks for your reply. Is there a program to obtain this ground truth region on a new model?

**Comment by wangg12** [comment]
It is computed online. Please check: https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/core/gdrn_modeling/data_loader.py#L535
