### ISSUE TITLE
关于数据集处理

### ISSUE THREAD

**Issue by JiangChen0639** [THU-DA-6D-Pose-Group/GDR-Net#105]
王博您好！首先感谢您的工作！请问您对linemod原始数据集做了什么处理？怎么处理的呢？谢谢。

**Comment by wangg12** [comment]
用的BOP处理后的lm数据，具体细节不是很清楚，大概就是有些3D模型重新对齐了中心，canonical pose也不太一样，另外数据集的结构变得更规范。
