### ISSUE TITLE
Can you open your onedrive?

### ISSUE THREAD

**Issue by stupidyoh** [THU-DA-6D-Pose-Group/GDR-Net#106]
Hello. I want to use your code.

But your onedrive link is blocked.

Can you open your onedrive or send me file of datasets and trained model?

**Comment by wangg12** [comment]
I no longer maintain the onedrive link. You can either download the files from BaiduNetDisk or refer to the new repo: https://github.com/shanice-l/gdrnpp_bop2022

**Comment by wangg12** [comment]
I updated the links in readme. The new Cloud.THU links should work.
