### ISSUE TITLE
Missing OneDrive Files

### ISSUE THREAD

**Issue by artium-rsipvision** [THU-DA-6D-Pose-Group/GDR-Net#111]
Hi,

The OneDrive links mentioned in the [datasets](https://github.com/THU-DA-6D-Pose-Group/GDR-Net#datasets) section of your readme lead to an error page: "The item might not exist or is no longer available".

Can you please re-upload those files so I can run the model training myself?

Thanks.

**Comment by wangg12** [comment]
I updated the links in readme. The new `Cloud.THU` links should work.
