### ISSUE TITLE
I'm having trouble with lm_pbr_1_gen_xyz_crop.py for my own 3d model

### ISSUE THREAD

**Issue by stupidyoh** [THU-DA-6D-Pose-Group/GDR-Net#115]
Hello.
Thank you for your nice work!

Anyway, I'm trying to train my own dataset.
When I run lm_pbr_1_gen_xyz_crop.py, it doesn't make any bgr_gl and depth_gl.
They consist only of numbers zero.
So, the code prints "not visible"

I checked "cam_R_m2c" and "cam_t_m2c" work well with my data.
And path to model and scene_gt.py also work well.
For mesh model, the only difference is that my 3D model doesn't have color information.

Is there any advice to solve this problem?

Thank you.

**Comment by wangg12** [comment]
Have you checked the unit of your model and cam_t_m2c?

**Comment by stupidyoh** [comment]
Thank you for your answer

Unfortunately, it doesn't work.
I found that linemod dataset has mm unit model scale and cam_t_m2c, but mine is m unit.
So I convert the unit of 3d model and scene.gt.
But still not work...

RGB image and visualization of 3d model and camera pose are below.
I think the cam_R_m2c and cam_t_m2c work well.

![스크린샷 2023-12-29 194706](https://github.com/THU-DA-6D-Pose-Group/GDR-Net/assets/121854081/9a1339f8-0d55-49a6-906f-a5991be96481)
![스크린샷 2023-12-29 194817](https://github.com/THU-DA-6D-Pose-Group/GDR-Net/assets/121854081/3304a492-ec2f-40de-9410-9096b0eccbf3)

P.S.
I wonder the value of "near" and "far" in following code.

bgr_gl, depth_gl = self.get_renderer().render(render_obj_id, IM_W, IM_H, K, R, t, near, far)

Is this the reason of my error?
And how can I get the value of near and far?
My camera is D435.

**Comment by wangg12** [comment]
near and far are some empirical values. For example, I always convert the model and the poses in m unit, thus near and far can be 0.01m and 100m so that the object is in the valid range of the renderer.

**Comment by stupidyoh** [comment]
Finally, I solve the problem.

In the past, my own dataset has m unit, so the translation matrix wasn't divided by 1000 compared to LM dataset.
But after converting unit m to mm, I still keep that code as it is.
Now it works well :)

Thank you very much for your quick response.
It helped me a lot.
