### ISSUE TITLE
请问这项工作有用到pvnet的网络结构吗

### ISSUE THREAD

**Issue by Zephyr-One** [THU-DA-6D-Pose-Group/GDR-Net#119]
我看项目路径下有core/gdrn_modeling/models/pvnet_net，但是好像没有看到别处在调用这部分，请问有用到这部分的代码来构建网络吗

**Comment by wangg12** [comment]
没有用到，之前尝试过，效果一般。

**Comment by Zephyr-One** [comment]
> 没有用到，之前尝试过，效果一般。

好的，谢谢~
