### ISSUE TITLE
Missing xyz_crop.pkl in the dataset

### ISSUE THREAD

**Issue by LounesDev** [THU-DA-6D-Pose-Group/GDR-Net#12]
Hi,

Congratulations for the CVPR paper and the great work.
I am trying to train the architecture on the Linemod dataset but it seems that the xyz_crop.pkl files are missing. And if I understand well, these files are crucial.
Have you planned to release them?

If not, what is the actual data structure of this file in order to generate it myself?

Thanks.

**Comment by wangg12** [comment]
Please refer to https://github.com/THU-DA-6D-Pose-Group/GDR-Net/issues/5

**Comment by wangg12** [comment]
See https://github.com/THU-DA-6D-Pose-Group/GDR-Net/pull/24
