### ISSUE TITLE
no fps_points.pkl

### ISSUE THREAD

**Issue by DC1991** [THU-DA-6D-Pose-Group/GDR-Net#17]
no  file 'BOP_DATASETS/lm/models/fps_points.pkl'

**Comment by DC1991** [comment]
find

**Comment by Sdy344** [comment]
I didn't find it either. Where did you find it

**Comment by DC1991** [comment]
@Sdy344 This git does provide it directly, you need to generate it by code in tools/lm/1_compute_fps.py
