### ISSUE TITLE
render data read

### ISSUE THREAD

**Issue by DC1991** [THU-DA-6D-Pose-Group/GDR-Net#19]
Thanks for your great work. How can I know the rendered data from PVNET is used for training, because the training code can smoothly run with or without the 'lm_renders_blender' folder.

**Comment by wangg12** [comment]
`DATASETS.TRAIN` should contain this kind of data.
https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/configs/gdrn/lmoSO/a6_cPnP_AugAAETrunc_BG0.5_lmoRealBl_160e_SO/a6_cPnP_AugAAETrunc_BG0.5_lmoRealBl_160e_ape.py#L42

**Comment by DC1991** [comment]
I see. So, the rendered dataset is optional here? Maybe you should write this in the readme file, since it takes time to generate this rendered dataset. Someone may choose not to generate this.
