### ISSUE TITLE
关于cuda版本的问题

### ISSUE THREAD

**Issue by fn6767** [THU-DA-6D-Pose-Group/GDR-Net#21]
您好，请问我使用cuda11以上的版本可以训练吗，因为我只有A6000和A100的显卡，它们不兼容cuda11以下的版本。我用cuda11.1和torch1.8或者1.9训练时，都会报double free or corruption (!prev)、RuntimeError: DataLoader worker (pid(s) xxxxx) exited unexpectedly。

**Comment by wangg12** [comment]
能用pytorch 1.7.1吗，1.8有问题，1.9我会试试

**Comment by wangg12** [comment]
1.8之前我测过确实有问题，pytorch官方有很多类似的issue, 我用1.9跑了下是没问题的，不过我没有A系列的显卡

**Comment by fn6767** [comment]
您用torch1.9跑没问题的cuda是cuda11吗？

**Comment by wangg12** [comment]
cuda 11也可以的

**Comment by fn6767** [comment]
我尝试了cuda11.1+torch1.9的配置，会报错malloc(): invalid size (unsorted)

**Comment by fn6767** [comment]
或者报malloc(): memory corruption

**Comment by peppa114** [comment]
> 能用pytorch 1.7.1吗，1.8有问题，1.9我会试试
你好，我尝试了pytorch1.7.1+cuda11.0,也是会有RuntimeError: DataLoader worker (pid(s) xxxxx) exited unexpectedly的报错，我用的是RTX3090显卡

**Comment by fn6767** [comment]
应该是内存不够，我开始也碰到了这个问题，把batch_size改小或者加大内存

**Comment by peppa114** [comment]
> 应该是内存不够，我开始也碰到了这个问题，把batch_size改小或者加大内存
我的机器内存应该是够的，有125g，之前尝试改了bath_size=12，中间还是会断，目前改成bath_size=2，运行正常，还没有断
![Screenshot from 2021-09-04 18-04-11](https://user-images.githubusercontent.com/83171253/132090795-a44a4c3e-3540-4464-ba05-466884eac8e2.png)

**Comment by peppa114** [comment]
> 应该是内存不够，我开始也碰到了这个问题，把batch_size改小或者加大内存

训练过程中，内存占用一直增加，不知道你是否知道如何解决这个问题
