### ISSUE TITLE
no file 'BOP_DATASETS/lm/models/fps_points.pkl

### ISSUE THREAD

**Issue by Sdy344** [THU-DA-6D-Pose-Group/GDR-Net#22]
我跑训练的时候，报错no file 'BOP_DATASETS/lm/models/fps_points.pkl，请问这个文件是在哪里得到呢？还有个问题是pvnet-rendering的代码python run.py --type rendering运行后，一个类只有10张图像生成，如何一个类生成1W张呢

**Comment by Sdy344** [comment]
i know

**Comment by liuicheng123** [comment]
你好，我也找不到这个文件，请问你最终解决了吗，能够给予我一些线索吗，谢谢

**Comment by Liuchongpei** [comment]
refer to https://github.com/THU-DA-6D-Pose-Group/GDR-Net/issues/17#issuecomment-894998747
