### ISSUE TITLE
关于可视化的问题

### ISSUE THREAD

**Issue by peppa114** [THU-DA-6D-Pose-Group/GDR-Net#27]
您好，请问如何可视化6D位姿？
得到像您论文中的这些图：
![1](https://user-images.githubusercontent.com/83171253/132211382-6267e9fb-94c3-4725-947b-727f9c6aa366.png)

**Comment by wangg12** [comment]
可以把物体的包围框在图像上进行投影实现。

**Comment by peppa114** [comment]
> 可以把物体的3D包围框在图像上进行投影实现。

我看到您提供有可视化的代码，可以麻烦稿告知一下具体该怎么实现吗？

**Comment by wangg12** [comment]
可以借鉴这里的实现哈 https://github.com/zju3dv/pvnet/blob/48e5066668f7563434373bc909b842a7bd94b7b9/lib/utils/draw_utils.py#L9

**Comment by peppa114** [comment]
感谢您的解答，我研究了一下这个代码，但我还是无法成功地实现可视化。我看到您在GDR-Net提供的代码中也有一些关于可视化的代码，请问是否有简单一点的可以实现的方法？十分感谢。
