### ISSUE TITLE
camera intrinsics matrix in pvnet-rendering

### ISSUE THREAD

**Issue by Liuchongpei** [THU-DA-6D-Pose-Group/GDR-Net#29]
Hello, I used pvnet-rendering to generate the synthetic dataset (lm_renders_blender) and trained the model. The evaluation results are far from those in the paper. I noticed that the camera intrinsic matrix in pvnet-rendering is  

     [[700, 0, 320],
     [0, 700, 240],
     [0, 0, 1]], 
which is different from that of linemod. Is it possible that this is the reason for the poor evaluation results?

**Comment by wangg12** [comment]
You need to adjust the camera intrinsic matrix.

**Comment by sunhan1997** [comment]
建议使用PVN3D提供的渲染工具，渲染更快，而且可以修改内参，另外，请问您渲染数据的gt.json文件是怎么生成的，方便给个参考吗？

**Comment by wangg12** [comment]
可以参考 https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/core/gdrn_modeling/datasets/lm_blender.py#L112
