### ISSUE TITLE
some question of the rot loss

### ISSUE THREAD

**Issue by Mr2er0** [THU-DA-6D-Pose-Group/GDR-Net#3]
It seems that the loss function used [here](https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/ea3dda76b3a6e37c08933730903105af5c95c305/configs/_base_/gdrn_base.py#L95) for rot is different from that in the paper. Is this better?

**Comment by wangg12** [comment]
By default it is not used
```
ROT_LOSS_TYPE="angular",  # angular | L2
ROT_LW=0.0,
```
