### ISSUE TITLE
what do these metrics mean?

### ISSUE THREAD

**Issue by liuicheng123** [THU-DA-6D-Pose-Group/GDR-Net#33]
what do these metrics mean? thanks for your answer!        
error_names = ["ad", "re", "te", "proj"]
        metric_names = [
            "ad_2",
            "ad_5",
            "ad_10",
            "rete_2",
            "rete_5",
            "rete_10",
            "re_2",
            "re_5",
            "re_10",
            "te_2",
            "te_5",
            "te_10",
            "proj_2",
            "proj_5",
            "proj_10",
        ]

**Comment by wangg12** [comment]
Please see the code around https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/core/gdrn_modeling/gdrn_custom_evaluator.py#L633
