### ISSUE TITLE
How to speed up training

### ISSUE THREAD

**Issue by Liuchongpei** [THU-DA-6D-Pose-Group/GDR-Net#36]
**_Phenomenon_**

GPU cannot maintain high utilization. The utilization rate of the CPU is always maintained at about 400% and cannot be improved (Our CPU has 32 cores and 64 threads).

**_What I did_**

Adjusting IMS_PER_BATCH, NUM_WORKERS in the configuration file, and OMP_NUM_THREADS and MKL_NUM_THREADS in train_gdrn.sh did not improve CPU utilization.

Do you have any good suggestions?

**Comment by wangg12** [comment]
Not sure, I am satisfied by the current speed.

**Comment by INGnowait** [comment]
> Not sure, I am satisfied by the current speed.

How long does it take you to train? Thk.

**Comment by wangg12** [comment]
For lm, < 10h.
