### ISSUE TITLE
pvnet-renderding如何修改blender相机内参

### ISSUE THREAD

**Issue by sunhan1997** [THU-DA-6D-Pose-Group/GDR-Net#37]
您好，请问您是如何解决pvnet-renderding修改blender相机内参的问题？如果要使用pvnet-renderding的数据，那就要渲染数据与测试相机内参相同，但blender好像是默认内参无法修改。。。。。。。。
另外您是否尝试过不是用lm的真实数据，只使用lm_imgn或者blender数据进行训练？我只使用lm_imgn进行训练，loss能够收敛，但评估结果全为0，加上40张lm的真实数据后才有效果

**Comment by sunhan1997** [comment]
放弃pvnet-rendering了，打算用pvn3d提供的渲染方法了，请问渲染数据的gt.json文件是否方便提供，作为参考也好

**Comment by wangg12** [comment]
gt.json就是将pvnet-rendering中每个图片有的gt合并了而已，自己按照代码中要求的标注格式也能整理出来，gt.json中的内容可参见https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/core/gdrn_modeling/datasets/lm_blender.py#L112。
