### ISSUE TITLE
alternative way to download the data?

### ISSUE THREAD

**Issue by RuyiLian** [THU-DA-6D-Pose-Group/GDR-Net#4]
Hi,

Thanks for sharing your code and data. However, downloading the data from BaiduNetDisk is extremely slow for me. Could you consider adding alternative links, e.g. Google drive? Thanks!

**Comment by wangg12** [comment]
Thanks for your interest! Unfortunately, I don't have enough space on Google Drive. But I have also uploaded them to OneDrive. Hope that helps.

**Comment by wangg12** [comment]
I updated the links in readme. The new Cloud.THU links should work.
