### ISSUE TITLE
如何获得faster_R50_FPN_AugCosyAAE_HalfAnchor_lmo_pbr_lmo_fuse_real_all_8e_test_480x640.json

### ISSUE THREAD

**Issue by peppa114** [THU-DA-6D-Pose-Group/GDR-Net#40]
我想做自己的多目标数据集，请问BOP_DATASETS\lmo\test\test_bboxes\faster_R50_FPN_AugCosyAAE_HalfAnchor_lmo_pbr_lmo_fuse_real_all_8e_test_480x640.json文件中包含的信息该如何获得？谢谢。

**Comment by wangg12** [comment]
这是检测结果，包含目标类别、检测框、检测分数等信息，具体可参见https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/7d20f108343a6ddf9d89b658e68985d10fbbefce/core/utils/dataset_utils.py#L147

**Comment by peppa114** [comment]
您好，我想再问一下，那个json文件中每张图片对应有30个obj_id，是指什么呢？谢谢。

**Comment by madhumilan** [comment]
Hi,

Could you please point me how to generate this particular file for testing LMO? **faster_R50_FPN_AugCosyAAE_HalfAnchor_lmo_pbr_lmo_fuse_real_all_8e_test_480x640.json**

Thanks.
