### ISSUE TITLE
Does this paper use the Information Of CAD models?

### ISSUE THREAD

**Issue by liuicheng123** [THU-DA-6D-Pose-Group/GDR-Net#41]
Well, I found that when we try to generate xyz_crop.pkl  It seems That we only use the depth map of a image,  Can we say that this is a net  Without the help of CAD model?
Or you use CAD model. But I didn't find it.
Thank you.

**Comment by wangg12** [comment]
The depth map for generating xyz should be the rendered depth from CAD models, because the real depth maps are noisy. So yes, we use the CAD information.

**Comment by liuicheng123** [comment]
> The depth map for generating xyz should be the rendered depth from CAD models, because the real depth maps are noisy. So yes, we use the CAD information.

  Thank you.but in #24  it doesn't use the CAD Information.

**Comment by wangg12** [comment]
It does. See https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/tools/lm/lm_pbr_1_gen_xyz_crop.py#L139
