### ISSUE TITLE
有没有pbr数据的渲染后的数据包呀

### ISSUE THREAD

**Issue by liuicheng123** [THU-DA-6D-Pose-Group/GDR-Net#44]
#24 中给出了两种生成pbr选然后的方法，第二种也是您给出的官方方法是直接用model计算出的，但是这个代码我运行bug太多，始终渲染不出，请问官方有没有你们生成的数据的镜像提供下载呀。感谢

**Comment by hellohaley** [comment]
你好，请问有没有官方提供的lmo的xyz_crop文件？
我在训练lmo数据集中因为缺失lmo/train_pbr/xyz_crop/000000/000000_000003-xyz.pkl文件无法继续。
使用 (https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/tools/lm/lm_pbr_1_gen_xyz_crop.py) 生成xyz_crop的过程中因为环境没装好所以遇到很多问题。
有没有官方提供的百度网盘或者OneDrive链接可供下载呀？感谢！

**Comment by wangg12** [comment]
没有。这个文件生成太耗硬盘存储了，后来我们都是在线生成训练的。
