### ISSUE TITLE
请问在训练过程中，cpu无法跑满怎么办

### ISSUE THREAD

**Issue by liuicheng123** [THU-DA-6D-Pose-Group/GDR-Net#48]
请问在训练过程中，cpu无法跑满怎么办
![image](https://user-images.githubusercontent.com/36021763/141131435-961f86ce-37a3-4bf3-b027-54f944b37fe6.png)
我跑了很多天了，设置多个num_workers后，cpu无法跑满，导致我的速度非常慢，这个怎么办呢。是和你们依托detectron有关吗，还是你别的原因，我看你们在代码中，好像是也有遇到相关问题吗

**Comment by wangg12** [comment]
不清楚，我没有关注cpu跑没跑满的问题，速度我觉得还可以。
