### ISSUE TITLE
files like 'datasets/BOP_DATASETS/lm/test/xyz_crop/000001/000004_000000.pkl' not found

### ISSUE THREAD

**Issue by lu-ming-lei** [THU-DA-6D-Pose-Group/GDR-Net#5]
I find this kind of data is not exit in bop_datasets, how can I get it? thanks.

**Comment by wangg12** [comment]
These are the labels for M_XYZ, i.e., the 3D object coordinates projected in the image space.
For now you need to manually generate them by:
* either render the coordinates using an OpenGL renderer 
* or get them by backprojecting the rendered depths.

Note that you need to also crop the patches by the 2D bounding box. 

We might also release the version which can generate the labels online, but not the near future unfortunately.

**Comment by lu-ming-lei** [comment]
Can you release some examples of 'xyz_cord' folders to show the structure, like 'image_sets' and 'test_bboxes'?

**Comment by wangg12** [comment]
'image_sets' and 'test_bboxes' have been uploaded to BaiduNetDisk/OneDrive.

Each xyz_crop pkl file is the cropped patch for each instance, it should be easy to understand the data structure https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/core/gdrn_modeling/data_loader.py#L464.

**Comment by makangzhe** [comment]
Thank you for your great work !  your code is as beautiful as a poem.  i can't wait to run it . can you release  xyz_crop pkl file which have finish labeled in BaiDuNetDist or OneDrive?

**Comment by wangg12** [comment]
> Thank you for your great work ! your code is as beautiful as a poem. i can't wait to run it . can you release xyz_crop pkl file which have finish labeled in BaiDuNetDist or OneDrive?

xyz_crop for lm and lm_imgn have been in BaiduNetDisk.

**Comment by wangg12** [comment]
... and OneDrive.
