### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by peppa114** [THU-DA-6D-Pose-Group/GDR-Net#51]
我训练完自己的多目标数据集后，得到.pth文件。请问我想测试一张新拍摄rgb图中多个物体的位姿，该怎么做？只用rgb图可以得到物体的Rt数据吗？十分感谢您的回答。

**Comment by wangg12** [comment]
需要训练一个检测器，目前我们是先存下来检测结果再输给GDR-Net预测。
不过你也可以改改测试代码，把检测器和GDR-Net的inference一起做了，需要一点点工作量。

**Comment by peppa114** [comment]
感谢您的回答，麻烦再问一下检测器是指什么？您保存的检测结果是什么数据呢？

**Comment by wangg12** [comment]
检测器是从图像中检测出物体的类别和2D位置和大小信息的网络，可以是Faster R-CNN, FCOS之类的。
检测结果是json数据，格式和样例见README Datasets部分 test_bboxes（网盘里）。

**Comment by peppa114** [comment]
好的十分感谢！那就是说我需要一张rgb图和test_bboxes信息这两个文件就可以了吗？

**Comment by peppa114** [comment]
好的十分感谢！那就是说我需要一张rgb图和test_bboxes信息这两个文件就可以了吗？

**Comment by wangg12** [comment]
还需要相机内参和物体的3D长宽高信息，这两个应该是你训练的时候就会有的。
3D长宽高是在网络预测归一化的3D坐标后，用于恢复尺度的。

**Comment by peppa114** [comment]
十分感谢！我的问题解决啦！

**Comment by peppa114** [comment]
十分感谢！我的问题解决啦！

**Comment by RoyAmoyal** [comment]
> 十分感谢！我的问题解决啦！

how did you manage to inference the results?(with 3d bounding box or pointcloud)

**Comment by peppa114** [comment]
> > 十分感谢！我的问题解决啦！
> 
> how did you manage to inference the results?(with 3d bounding box or pointcloud)

After obtaining the rgb image, you need to use a target detector(such as faster rcnn) to detect the bounding box of the object in the figure and write the bounding box information to the file(test_bboxes).
