### ISSUE TITLE
using database acquired with different cameras

### ISSUE THREAD

**Issue by mht1421** [THU-DA-6D-Pose-Group/GDR-Net#55]
Hi, I tried to feed the network with a database acquired different cameras (different calibrations + distortion coefficients), I have 2 questions:
- can the network handle cameras having distortion coefficients?
- can the Patch-PnP learn different calibrations of different cameras?

**Comment by wangg12** [comment]
Dealing with different cameras is not considered in this work, so some effort might be needed to make it work. BTW, I think this is an interesting and important point to investigate.
