### ISSUE TITLE
Could you open-source the DEBUG part of this repo?

### ISSUE THREAD

**Issue by cuge1995** [THU-DA-6D-Pose-Group/GDR-Net#56]
Thanks for the great work.
However, when I open the DEBUG mode, bugs occurs.
```
gdrn_custom_evaluator.py", line 79, in __init__
    from lib.render_vispy.model3d import load_models
ModuleNotFoundError: No module named 'lib.render_vispy'
```

**Comment by wangg12** [comment]
Hey, these are just for visualization. You can use this https://github.com/thodan/bop_toolkit/blob/master/bop_toolkit_lib/renderer_vispy.py (also written by me), and implement your own visualization code.
