### ISSUE TITLE
Missing data when training lmo

### ISSUE THREAD

**Issue by cuge1995** [THU-DA-6D-Pose-Group/GDR-Net#59]
Dear authors, where is this file?
```
lmo/train_pbr/xyz_crop/000000/000000_000003-xyz.pkl
```

**Comment by wangg12** [comment]
Please refer to https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/tools/lm/lm_pbr_1_gen_xyz_crop.py, you only need to modify a few lines to adapt it for lmo.
