### ISSUE TITLE
Pipeline to print inferred 3D bounding boxes on images

### ISSUE THREAD

**Issue by AlbertoRemus** [THU-DA-6D-Pose-Group/GDR-Net#64]
Hello! I find this work really interesting. After successfully testing inference (LMO and YCB) I was just interested in plotting the inference results as 3D bounding boxes on RGB images and by inspecting the code I bumped into:

https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/5fb30c3dc53f46bac24a8a83a373eac7a8038556/core/gdrn_modeling/gdrn_evaluator.py#L516

it is the function used for inference, which seems to show the results in terms of the different metrics, but not showing graphical results as I am looking for

In the same file I noticed the function:
https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/5fb30c3dc53f46bac24a8a83a373eac7a8038556/core/gdrn_modeling/gdrn_evaluator.py#L634

which seems structurally similar but with some input differences, in particular I would like to ask if the input dataloader can be be computed for `gdrn_inference_on_dataset` as for `save_result_of_dataset` as in

https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/5fb30c3dc53f46bac24a8a83a373eac7a8038556/core/gdrn_modeling/engine.py#L135-L137

Since from preliminar debugging it seems it is not possible to access to the `"image"` field of the input sample in

https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/5fb30c3dc53f46bac24a8a83a373eac7a8038556/core/gdrn_modeling/gdrn_evaluator.py#L678

Possibly related issue: https://github.com/THU-DA-6D-Pose-Group/GDR-Net/issues/56

**Comment by wangg12** [comment]
If you want to access "image" during test, you need to change the dataloader https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/5fb30c3dc53f46bac24a8a83a373eac7a8038556/core/gdrn_modeling/data_loader.py#L368

**Comment by Liuchongpei** [comment]
@wangg12 Your work is very meaningful. Can you tell me where the code for visualizing 6D pose is as shown in the figure below？

![2345截图20211212205335](https://user-images.githubusercontent.com/34116796/145713319-23e7f67c-c338-4a9c-be9f-b345de5486a9.jpg)

**Comment by AlbertoRemus** [comment]
> If you want to access "image" during test, you need to change the dataloader

Many thanks, actually by inspecting the code, I realized that I don't need the image to be inside the image field (I could load it directly from disk), I think would just need the 8-vertex bounding box in pixel coordinates to be returned among the results datastructure that at the moment contain only rotation and translation

**Comment by AlbertoRemus** [comment]
> Many thanks, actually by inspecting the code, I realized that I don't need the image to be inside the image field (I could load it directly from disk), I think I would just need the 8-vertex bounding box in pixel coordinates to be returned among the results datastructure that at the moment contain only rotation and translation

With the modifications in my fork https://github.com/AlbertoRemus/GDR-Net/commit/005123e83d51a210a49b196f1908db00517dbec8 you can see what I was looking for (blue ground truth, red prediction):

![1118_gdr_net](https://user-images.githubusercontent.com/54797872/146683041-00567b89-b2d5-45a8-8ab7-e161da8e80b3.gif)

Initially I hadn't realize that given:
* the 3D model
* matrices R, t (ground truth and predicted)
* matrix K intrinsic parameters

It is straight forward to compute the 2D projection of the model points on the image plane

**Comment by AlbertoRemus** [comment]
Provided the solution found in https://github.com/THU-DA-6D-Pose-Group/GDR-Net/issues/64#issuecomment-997423316 I would close this issue (@wangg12 let me know if you need these modifications upstream I can open a PR)

@Liuchongpei your question is interesting, it may be worth to open a separate issue for that to visualize that plot with the segmentation mask

**Comment by AlbertoRemus** [comment]
> > https://github.com/THU-DA-6D-Pose-Group/GDR-Net/issues/64#issuecomment-991894371

> @Liuchongpei your question is interesting, it may be worth to open a separate issue for that to visualize that plot with the segmentation mask

This quick and dirty modification should do the job: https://github.com/AlbertoRemus/GDR-Net/commit/6926865fef78e7f9e8264ed6bfae184a49cbcdb3

![1118_gdr_net_10_seg](https://user-images.githubusercontent.com/54797872/147106317-eb637d27-6246-4631-97b9-0074822256d8.gif)

**Comment by cuge1995** [comment]
> should

Hey, I can't find the branch you mentioned, do anything wrong ?

**Comment by AlbertoRemus** [comment]
> Hey, I can't find the branch you mentioned, does anything wrong?

Hi, I should have fixed the links!
