### ISSUE TITLE
 xyz_crop是mask吗？ 还是论文中提到的Mxyz?

### ISSUE THREAD

**Issue by Vain-Glory** [THU-DA-6D-Pose-Group/GDR-Net#65]
![`8EKETS~Z0HE@{XPO4KXFD6](https://user-images.githubusercontent.com/22914012/145219340-a48831b2-2f85-4c53-8195-898e3461853f.png)

**Comment by wangg12** [comment]
Mxyz

**Comment by Vain-Glory** [comment]
明白了 感谢您的解答
