### ISSUE TITLE
小白问一下环境配置的问题

### ISSUE THREAD

**Issue by micki-37** [THU-DA-6D-Pose-Group/GDR-Net#66]
requirment.txt里面的包和readme文档里需要装的好像不太一样，是两部分提到的都需要装吗

**Comment by wangg12** [comment]
应该没有不同

**Comment by micki-37** [comment]
我看readme里的要求有cuda torch torchvision和一个叫detectron的包 但好像requirement.txt里没这个detectron 也没有torch只有一个torchlightning&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Gu Wang ***@***.***&gt;
发送时间: 2021年12月14日 16:37
收件人: THU-DA-6D-Pose-Group/GDR-Net ***@***.***&gt;
抄送: micki-37 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [THU-DA-6D-Pose-Group/GDR-Net] 小白问一下环境配置的问题 (Issue #66)





 
应该没有不同
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangg12** [comment]
您按照readme步骤安装即可

**Comment by micki-37** [comment]
ok 那torch版本有要求吗 还有就是那个detectron2的预编译包需要安装吗





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Gu Wang ***@***.***&gt;
发送时间: 2021年12月14日 16:42
收件人: THU-DA-6D-Pose-Group/GDR-Net ***@***.***&gt;
抄送: micki-37 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [THU-DA-6D-Pose-Group/GDR-Net] 小白问一下环境配置的问题 (Issue #66)





 
您按照readme步骤安装即可
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Vain-Glory** [comment]
我今天想跑这个代码时候也在detectron2出问题了。。

**Comment by micki-37** [comment]
我不知道怎么配置环境 你是requirement txt 和他readme里的那个requirement都装了吗





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Vain-Glory ***@***.***&gt;
发送时间: 2021年12月14日 21:08
收件人: THU-DA-6D-Pose-Group/GDR-Net ***@***.***&gt;
抄送: micki-37 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [THU-DA-6D-Pose-Group/GDR-Net] 小白问一下环境配置的问题 (Issue #66)





 
我今天想跑这个代码时候也在detectron2出问题了。。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by micki-37** [comment]
> 我今天想跑这个代码时候也在detectron2出问题了。。

加个vx交流一下？15319759308
