### ISSUE TITLE
Influence of the size of intermediate geometric features

### ISSUE THREAD

**Issue by Liuchongpei** [THU-DA-6D-Pose-Group/GDR-Net#68]
I noticed that the size of intermediate geometric features is *×64×64. What happens if the size changes? (E.g., *×128×128, *×256×256)

**Comment by wangg12** [comment]
The size was inherited from CDPN, I didn't test larger sizes. You can try them and see what happens (maybe also let us know). Basically, I would expect them to be slower but not bad.

**Comment by Liuchongpei** [comment]
Okay, thank you.
