### ISSUE TITLE
关于安装detectron2的问题

### ISSUE THREAD

**Issue by Ethan-shen-lab** [THU-DA-6D-Pose-Group/GDR-Net#69]
我是按照GDR-Net的Requirements在Ubuntu16.04安装了CUDA10.1,CUDNN,还有pytorch1.7和torchvision0.8，但是我看到detectron2的安装指南里要求pytorch至少1.8，请问1.7的版本可以吗？
![image](https://user-images.githubusercontent.com/74591670/150082534-9f6ce71d-555c-4bc6-afc6-4ba05ea74562.png)

**Comment by wangg12** [comment]
可能可以，我没测试过
