### ISSUE TITLE
Rotation Error and Symmetries

### ISSUE THREAD

**Issue by FabianSchuetze** [THU-DA-6D-Pose-Group/GDR-Net#70]
Thanks for this wonderful paper and the repo - both are a pleasure to read. 

I am thinking about the computation of the rotation loss. 

First, should the `pred_rot_m` be replaced by `pred_rot_ego` in the computation of the [rotation loss](https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/8bd8f781a8293fa6e2628a7d806fe61a8126b6b7/core/gdrn_modeling/models/GDRN.py#L246)?
```
            mean_re, mean_te = compute_mean_re_te(pred_trans, pred_rot_m, gt_trans, gt_ego_rot) 
```
Should the symmetries also be passed into this function? 

Second, I think for the lm models, the parameter for the [PyPMLoss](https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/8bd8f781a8293fa6e2628a7d806fe61a8126b6b7/core/gdrn_modeling/models/GDRN.py#L405) regulating the use of the symmetric loss `symmetric=pnp_net_cfg.PM_LOSS_SYM` is set to `False`. Can this be?

**Comment by wangg12** [comment]
Hi, thanks for your interest in our work!

1. Yes, the `pred_rot_m` be replaced by `pred_rot_ego` in 
```
mean_re, mean_te = compute_mean_re_te(pred_trans, pred_rot_m, gt_trans, gt_ego_rot)
```
but this is not for computing the loss. It is just for debug and visualization back then. I forgot to change it at some point. The one for loss computation is correct. 

2. For LINEMOD, the symmetric one and the non-symmetric one are almost the same. The explanation could be found in the paper.

**Comment by FabianSchuetze** [comment]
Thanks for your reply and detailed explanations! I re-read the description of the symmetries in the paper - thanks for pointing it out again.
