### ISSUE TITLE
Generation of xyz_crop for YCB-V

### ISSUE THREAD

**Issue by AlbertoRemus** [THU-DA-6D-Pose-Group/GDR-Net#71]
Hello, while trying to perform a training on YCB-V dataset I bumped into thte following error::

```
20220203_102832|core.gdrn_modeling.datasets.ycbv_d2@277: loading dataset dicts: ycbv_train_real
  0%|          | 0/113198 [00:00<?, ?it/s]
20220203_102837|ERR|__main__@168: An error has been caught in function '<module>', process 'MainProcess' (30), thread 'MainThread' (139815105783616):
Traceback (most recent call last):

> File "/home/object_pose_estimation/GDR-Net/core/gdrn_modeling/main_gdrn.py", line 168, in <module>
    main(args)
    │    └ Namespace(config_file='configs/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_Rsym_ycbv_real_pbr_visib20_10e.py', resume=False, eval_onl...
    └ <function main at 0x7f278896c160>

  File "/home/object_pose_estimation/GDR-Net/core/gdrn_modeling/main_gdrn.py", line 136, in main
    Lite(
    └ <class '__main__.Lite'>

  File "/home/object_pose_estimation/GDR-Net/env/lib/python3.9/site-packages/pytorch_lightning/lite/lite.py", line 403, in _run_impl
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='configs/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_Rsym_ycbv_real_pbr_visib20_10e.py', resume=False, eval_on...
           └ functools.partial(<bound method LightningLite._run_with_sharded_context of <__main__.Lite object at 0x7f293ce35580>>, <bound ...
  File "/home/object_pose_estimation/GDR-Net/env/lib/python3.9/site-packages/pytorch_lightning/lite/lite.py", line 407, in _run_with_sharded_context
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='configs/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_Rsym_ycbv_real_pbr_visib20_10e.py', resume=False, eval_on...
           └ <bound method Lite.run of <__main__.Lite object at 0x7f293ce35580>>

  File "/home/object_pose_estimation/GDR-Net/core/gdrn_modeling/main_gdrn.py", line 124, in run
    self.do_train(cfg, args, model, optimizer, resume=args.resume)
    │    │        │    │     │      │                 │    └ False
    │    │        │    │     │      │                 └ Namespace(config_file='configs/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_Rsym_ycbv_real_pbr_visib20_10e.py', resume=False, eval_onl...
    │    │        │    │     │      └ LiteRanger (
    │    │        │    │     │        Parameter Group 0
    │    │        │    │     │            N_sma_threshhold: 5
    │    │        │    │     │            alpha: 0.5
    │    │        │    │     │            betas: (0.95, 0.999)
    │    │        │    │     │            eps: 1e-05
    │    │        │    │     │            k: 6
    │    │        │    │     │            lr...
    │    │        │    │     └ _LiteModule(
    │    │        │    │         (_module): GDRN(
    │    │        │    │           (backbone): ResNetBackboneNet(
    │    │        │    │             (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2...
    │    │        │    └ Namespace(config_file='configs/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_Rsym_ycbv_real_pbr_visib20_10e.py', resume=False, eval_onl...
    │    │        └ Config (path: configs/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_Rsym_ycbv_real_pbr_visib20_10e.py): {'OUTPUT_ROOT': 'output', 'OUTP...
    │    └ <function GDRN_Lite.do_train at 0x7f2788e7a9d0>
    └ <__main__.Lite object at 0x7f293ce35580>

  File "/home/object_pose_estimation/GDR-Net/core/gdrn_modeling/../../core/gdrn_modeling/engine.py", line 155, in do_train
    data_loader = build_gdrn_train_loader(cfg, train_dset_names)
                  │                       │    └ ('ycbv_train_real', 'ycbv_train_pbr')
                  │                       └ Config (path: configs/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_Rsym_ycbv_real_pbr_visib20_10e.py): {'OUTPUT_ROOT': 'output', 'OUTP...
                  └ <function build_gdrn_train_loader at 0x7f278a942820>

  File "/home/object_pose_estimation/GDR-Net/core/gdrn_modeling/../../core/gdrn_modeling/data_loader.py", line 675, in build_gdrn_train_loader
    dataset_dicts = get_detection_dataset_dicts(
                    └ <function get_detection_dataset_dicts at 0x7f2846b105e0>

  File "/home/object_pose_estimation/GDR-Net/env/lib/python3.9/site-packages/detectron2/data/build.py", line 241, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
                     │              │                                     └ ('ycbv_train_real', 'ycbv_train_pbr')
                     │              └ <function _DatasetCatalog.get at 0x7f2846ba7160>
                     └ DatasetCatalog(registered datasets: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_t...
  File "/home/object_pose_estimation/GDR-Net/env/lib/python3.9/site-packages/detectron2/data/build.py", line 241, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
                     │              │   │                 └ 'ycbv_train_real'
                     │              │   └ 'ycbv_train_real'
                     │              └ <function _DatasetCatalog.get at 0x7f2846ba7160>
                     └ DatasetCatalog(registered datasets: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_t...
  File "/home/object_pose_estimation/GDR-Net/env/lib/python3.9/site-packages/detectron2/data/catalog.py", line 58, in get
    return f()
           └ <core.gdrn_modeling.datasets.ycbv_d2.YCBV_Dataset object at 0x7f2788902e80>

  File "/home/object_pose_estimation/GDR-Net/core/gdrn_modeling/../../core/gdrn_modeling/datasets/ycbv_d2.py", line 283, in __call__
    dataset_dicts.extend(self._load_from_idx_file(ann_file, image_root))
    │             │      │    │                   │         └ '/home/object_pose_estimation/GDR-Net/datasets/BOP_DATASETS/ycbv/train_real'
    │             │      │    │                   └ '/home/object_pose_estimation/GDR-Net/datasets/BOP_DATASETS/ycbv/image_sets/train.txt'
    │             │      │    └ <function YCBV_Dataset._load_from_idx_file at 0x7f278ab67b80>
    │             │      └ <core.gdrn_modeling.datasets.ycbv_d2.YCBV_Dataset object at 0x7f2788902e80>
    │             └ <method 'extend' of 'list' objects>
    └ []

  File "/home/object_pose_estimation/GDR-Net/core/gdrn_modeling/../../core/gdrn_modeling/datasets/ycbv_d2.py", line 226, in _load_from_idx_file
    assert osp.exists(xyz_path), xyz_path
           │   │      │          └ '/home/object_pose_estimation/GDR-Net/datasets/BOP_DATASETS/ycbv/train_real/xyz_crop/000000/000001_000000-xyz.pkl'
           │   │      └ '/home/object_pose_estimation/GDR-Net/datasets/BOP_DATASETS/ycbv/train_real/xyz_crop/000000/000001_000000-xyz.pkl'
           │   └ <function exists at 0x7f293da393a0>
           └ <module 'posixpath' from '/home/object_pose_estimation/GDR-Net/env/lib/python3.9/posixpath.py'>

AssertionError: /home/object_pose_estimation/GDR-Net/datasets/BOP_DATASETS/ycbv/train_real/xyz_crop/000000/000001_000000-xyz.pkl
```

In fact `BOP_DATASETS/ycbv/train_real/xyz_crop/000000/000001_000000-xyz.pkl` is not present in my filesystem, and I was wondering whether I need to generate `xyz_crop` by taking inspiration from https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/tools/lm/lm_pbr_1_gen_xyz_crop.py

**Comment by wangg12** [comment]
Yes. You can refer to the one for lm and modify it for other datasets.

**Comment by 599-liu** [comment]
@AlbertoRemus Hello, have you solved this problem? Thanks

**Comment by Zephyr-One** [comment]
> Hello, while trying to perform a training on YCB-V dataset I bumped into thte following error::
> 
> ```
> 20220203_102832|core.gdrn_modeling.datasets.ycbv_d2@277: loading dataset dicts: ycbv_train_real
>   0%|          | 0/113198 [00:00<?, ?it/s]
> 20220203_102837|ERR|__main__@168: An error has been caught in function '<module>', process 'MainProcess' (30), thread 'MainThread' (139815105783616):
> Traceback (most recent call last):
> 
> > File "/home/object_pose_estimation/GDR-Net/core/gdrn_modeling/main_gdrn.py", line 168, in <module>
>     main(args)
>     │    └ Namespace(config_file='configs/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_Rsym_ycbv_real_pbr_visib20_10e.py', resume=False, eval_onl...
>     └ <function main at 0x7f278896c160>
> 
>   File "/home/object_pose_estimation/GDR-Net/core/gdrn_modeling/main_gdrn.py", line 136, in main
>     Lite(
>     └ <class '__main__.Lite'>
> 
>   File "/home/object_pose_estimation/GDR-Net/env/lib/python3.9/site-packages/pytorch_lightning/lite/lite.py", line 403, in _run_impl
>     return run_method(*args, **kwargs)
>            │           │       └ {}
>            │           └ (Namespace(config_file='configs/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_Rsym_ycbv_real_pbr_visib20_10e.py', resume=False, eval_on...
>            └ functools.partial(<bound method LightningLite._run_with_sharded_context of <__main__.Lite object at 0x7f293ce35580>>, <bound ...
>   File "/home/object_pose_estimation/GDR-Net/env/lib/python3.9/site-packages/pytorch_lightning/lite/lite.py", line 407, in _run_with_sharded_context
>     return run_method(*args, **kwargs)
>            │           │       └ {}
>            │           └ (Namespace(config_file='configs/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_Rsym_ycbv_real_pbr_visib20_10e.py', resume=False, eval_on...
>            └ <bound method Lite.run of <__main__.Lite object at 0x7f293ce35580>>
> 
>   File "/home/object_pose_estimation/GDR-Net/core/gdrn_modeling/main_gdrn.py", line 124, in run
>     self.do_train(cfg, args, model, optimizer, resume=args.resume)
>     │    │        │    │     │      │                 │    └ False
>     │    │        │    │     │      │                 └ Namespace(config_file='configs/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_Rsym_ycbv_real_pbr_visib20_10e.py', resume=False, eval_onl...
>     │    │        │    │     │      └ LiteRanger (
>     │    │        │    │     │        Parameter Group 0
>     │    │        │    │     │            N_sma_threshhold: 5
>     │    │        │    │     │            alpha: 0.5
>     │    │        │    │     │            betas: (0.95, 0.999)
>     │    │        │    │     │            eps: 1e-05
>     │    │        │    │     │            k: 6
>     │    │        │    │     │            lr...
>     │    │        │    │     └ _LiteModule(
>     │    │        │    │         (_module): GDRN(
>     │    │        │    │           (backbone): ResNetBackboneNet(
>     │    │        │    │             (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2...
>     │    │        │    └ Namespace(config_file='configs/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_Rsym_ycbv_real_pbr_visib20_10e.py', resume=False, eval_onl...
>     │    │        └ Config (path: configs/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_Rsym_ycbv_real_pbr_visib20_10e.py): {'OUTPUT_ROOT': 'output', 'OUTP...
>     │    └ <function GDRN_Lite.do_train at 0x7f2788e7a9d0>
>     └ <__main__.Lite object at 0x7f293ce35580>
> 
>   File "/home/object_pose_estimation/GDR-Net/core/gdrn_modeling/../../core/gdrn_modeling/engine.py", line 155, in do_train
>     data_loader = build_gdrn_train_loader(cfg, train_dset_names)
>                   │                       │    └ ('ycbv_train_real', 'ycbv_train_pbr')
>                   │                       └ Config (path: configs/gdrn/ycbv/a6_cPnP_AugAAETrunc_BG0.5_Rsym_ycbv_real_pbr_visib20_10e.py): {'OUTPUT_ROOT': 'output', 'OUTP...
>                   └ <function build_gdrn_train_loader at 0x7f278a942820>
> 
>   File "/home/object_pose_estimation/GDR-Net/core/gdrn_modeling/../../core/gdrn_modeling/data_loader.py", line 675, in build_gdrn_train_loader
>     dataset_dicts = get_detection_dataset_dicts(
>                     └ <function get_detection_dataset_dicts at 0x7f2846b105e0>
> 
>   File "/home/object_pose_estimation/GDR-Net/env/lib/python3.9/site-packages/detectron2/data/build.py", line 241, in get_detection_dataset_dicts
>     dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
>                      │              │                                     └ ('ycbv_train_real', 'ycbv_train_pbr')
>                      │              └ <function _DatasetCatalog.get at 0x7f2846ba7160>
>                      └ DatasetCatalog(registered datasets: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_t...
>   File "/home/object_pose_estimation/GDR-Net/env/lib/python3.9/site-packages/detectron2/data/build.py", line 241, in <listcomp>
>     dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
>                      │              │   │                 └ 'ycbv_train_real'
>                      │              │   └ 'ycbv_train_real'
>                      │              └ <function _DatasetCatalog.get at 0x7f2846ba7160>
>                      └ DatasetCatalog(registered datasets: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_t...
>   File "/home/object_pose_estimation/GDR-Net/env/lib/python3.9/site-packages/detectron2/data/catalog.py", line 58, in get
>     return f()
>            └ <core.gdrn_modeling.datasets.ycbv_d2.YCBV_Dataset object at 0x7f2788902e80>
> 
>   File "/home/object_pose_estimation/GDR-Net/core/gdrn_modeling/../../core/gdrn_modeling/datasets/ycbv_d2.py", line 283, in __call__
>     dataset_dicts.extend(self._load_from_idx_file(ann_file, image_root))
>     │             │      │    │                   │         └ '/home/object_pose_estimation/GDR-Net/datasets/BOP_DATASETS/ycbv/train_real'
>     │             │      │    │                   └ '/home/object_pose_estimation/GDR-Net/datasets/BOP_DATASETS/ycbv/image_sets/train.txt'
>     │             │      │    └ <function YCBV_Dataset._load_from_idx_file at 0x7f278ab67b80>
>     │             │      └ <core.gdrn_modeling.datasets.ycbv_d2.YCBV_Dataset object at 0x7f2788902e80>
>     │             └ <method 'extend' of 'list' objects>
>     └ []
> 
>   File "/home/object_pose_estimation/GDR-Net/core/gdrn_modeling/../../core/gdrn_modeling/datasets/ycbv_d2.py", line 226, in _load_from_idx_file
>     assert osp.exists(xyz_path), xyz_path
>            │   │      │          └ '/home/object_pose_estimation/GDR-Net/datasets/BOP_DATASETS/ycbv/train_real/xyz_crop/000000/000001_000000-xyz.pkl'
>            │   │      └ '/home/object_pose_estimation/GDR-Net/datasets/BOP_DATASETS/ycbv/train_real/xyz_crop/000000/000001_000000-xyz.pkl'
>            │   └ <function exists at 0x7f293da393a0>
>            └ <module 'posixpath' from '/home/object_pose_estimation/GDR-Net/env/lib/python3.9/posixpath.py'>
> 
> AssertionError: /home/object_pose_estimation/GDR-Net/datasets/BOP_DATASETS/ycbv/train_real/xyz_crop/000000/000001_000000-xyz.pkl
> ```
> 
> In fact `BOP_DATASETS/ycbv/train_real/xyz_crop/000000/000001_000000-xyz.pkl` is not present in my filesystem, and I was wondering whether I need to generate `xyz_crop` by taking inspiration from https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/tools/lm/lm_pbr_1_gen_xyz_crop.py

Hello, could you share your code? Thanks!
