### ISSUE TITLE
Question about region loss

### ISSUE THREAD

**Issue by AlbertoRemus** [THU-DA-6D-Pose-Group/GDR-Net#72]
Hello, I've got one question related to the final loss function at the end of training on LM dataset:

```
20220202_214644|core.utils.my_writer:write@171: eta: 0:00:00 iter: 102399/102400[100.0%] 
lr: 3.0014e-13
total_grad_norm: N/A
total_loss: 1.4331e+01 (1.5022e+01)
loss_coor_x: 1.0531e-02 (2.1616e-02)
loss_coor_y: 1.1358e-02 (2.2144e-02)
loss_coor_z: 1.1151e-02 (2.1129e-02)
loss_mask: 1.1224e-02 (2.1068e-02)
loss_region: 1.4266e+01 (1.4841e+01)
loss_PM_R: 1.0242e-02 (3.6415e-02)
loss_centroid: 4.3279e-03 (1.1124e-02)
loss_z: 9.0583e-03 (4.7604e-02)
```

I was curious about the ` loss_region: 1.4266e+01 (1.4841e+01)` which appears to be _3 orders of magnitude_ bigger than all the other losses and I was wondering whether this may be possibly related to a problematic training

**Comment by wangg12** [comment]
I think it is normal, because the channels for the region loss is the number of regions (e.g. 65), so it can be much bigger than other losses. From the final results, I think the training should be alright.
