### ISSUE TITLE
Why only 13 objects are used when training linemod?

### ISSUE THREAD

**Issue by zeal-github** [THU-DA-6D-Pose-Group/GDR-Net#75]
Why do you exclude bowl and cup from the training linemod dataset in your official config?
I cannot find such operations in the paper. Is the paper's result using 15 linemod objects or the 13 objects?

Oh, by the way, I use your config and produce a close result in linemod reported by your paper!! It help me a lot !! Thanks!!

**Comment by wangg12** [comment]
The results are reported using 13 objects on LM. Because almost all of the previous works only report the results of 13 objects. You can refer to those papers for the explanation.
