### ISSUE TITLE
运行gen_xyz_crop时报错EGLError= EGL_NOT_INITIALIZED

### ISSUE THREAD

**Issue by lyj9494** [THU-DA-6D-Pose-Group/GDR-Net#76]
您好，我正在运行lm_pbr_1_gen_xyz_crop.py文件，出现了这样的错误，可以请问一下怎样才能解决吗
![image](https://user-images.githubusercontent.com/91005527/162583017-9737f8f4-4345-4df0-a407-1e53f1b5186a.png)

**Comment by wangg12** [comment]
这个可能可以参考下 https://github.com/DLR-RM/AugmentedAutoencoder/pull/42

**Comment by zhaoxuefengeric** [comment]
@lyj9494 您好，我在docker镜像中运行xyz_crop生成脚本时遇到了和您一样的问题，请问你可以详细说一下您的配置情况以及解决方案嘛。十分感谢您的回复

**Comment by wangg12** [comment]
用或者自己构建带有cudagl的docker，驱动最好也装opengl cuda driver
