### ISSUE TITLE
Proportion of pbr dataset selected for training

### ISSUE THREAD

**Issue by lu-ming-lei** [THU-DA-6D-Pose-Group/GDR-Net#77]
in configs,   like in a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e.py ,   TRAIN2_RATIO=0.1,
and in engine.py 
if train_2_ratio > 0.0 and len(train_2_dset_names) > 0:
        data_loader_2 = build_gdrn_train_loader(cfg, train_2_dset_names)
        data_loader_2_iter = iter(data_loader_2)
shows all pbr datasets are used for training.
Do you use the full pbr dataset in training?

**Comment by wangg12** [comment]
Yes, the full pbr.
