### ISSUE TITLE
xyzcrop生成程序的问题

### ISSUE THREAD

**Issue by mate-huaboy** [THU-DA-6D-Pose-Group/GDR-Net#78]
王博，各位大佬们，我在使用tools/lm/lm_pbr_1_gen_xyz_crop.py程序时，opengl初始化环境时一直报错，报的错误如下：

File "/home/lyn/anaconda3/envs/lyn/lib/python3.7/site-packages/OpenGL/error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.raw.EGL._errors.EGLError: EGLError(
        err = EGL_NOT_INITIALIZED,
        baseOperation = eglInitialize,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7f79042eccb0>,
                c_long(0),
                c_long(0),
        ),
        result = 0
)
寻找的解决方法都没能解决我的问题，请问有人知道解决方法吗，或者有人能分析一下原因吗

**Comment by wangg12** [comment]
参考下这个 https://github.com/THU-DA-6D-Pose-Group/GDR-Net/issues/76

**Comment by mate-huaboy** [comment]
> 参考下这个 #76

感谢您的回复，我解决问题了！是因为驱动的问题，因为用的别人的电脑一直没有敢动系统层面的事情，找了快一周的解决方法最后确定一定是驱动的问题，重装就可以了，其他人有类似的问题可以使用glxinfo | grep OpenGL查看确认opengl是不是正确使用驱动了！

**Comment by wangg12** [comment]
驱动问题除了docker以外，也可参考我在这里提到的驱动： https://github.com/thodan/bop_toolkit#vispy-renderer-default

**Comment by micki-37** [comment]
> > 参考下这个 #76
> 
> 感谢您的回复，我解决问题了！是因为驱动的问题，因为用的别人的电脑一直没有敢动系统层面的事情，找了快一周的解决方法最后确定一定是驱动的问题，重装就可以了，其他人有类似的问题可以使用glxinfo | grep OpenGL查看确认opengl是不是正确使用驱动了！

您好，我也遇到了类似的问题，您能再说的详细点吗 @mate-huaboy
