### ISSUE TITLE
关于训练的时候使用数据集问题

### ISSUE THREAD

**Issue by mate-huaboy** [THU-DA-6D-Pose-Group/GDR-Net#80]
王博，您好。您的工作对我启发很大，我准备在您的工作的基础上继续我的工作，但是我在用您的代码训练时（目前仅修改到了在linemod数据集上的训练）我发现您训练是在测试集上进行的，我想问一下我的理解是正确的吗？如果正确，这样做（在测试集上训练）的有什么好处或者目的在那儿，为什么没有利用训练集训练呢，另外，请问其他两个数据集（linemod-O和YCB-V）上的训练也是这样设置的吗，即也是在测试集上训练的吗。目前很需要您的回答，期待您的回答！万分感谢

**Comment by wangg12** [comment]
LM数据集的真实数据存放的文件夹名是test，不代表我们的方法是在测试集上训练的。关于训练测试的划分，我们严格遵循所对比的方法里面的设定，你可以在我们的文章以及我们对比的方法的文章里找到对应的描述，请仔细阅读相关文献，谢谢。
