### ISSUE TITLE
关于pytorch版本的问题

### ISSUE THREAD

**Issue by lu-ming-lei** [THU-DA-6D-Pose-Group/GDR-Net#81]
感谢您更新了新版本的代码。
在旧版本中，我使用配置 pytorch=1.7.0，cuda=10.1，detection=0.4 可以跑通代码
新版中用到了pytorch-lightning，这个需要pytorch版本在1.8.0及以上，我在其他问题中看到您有说pytorch版本在1.8.0及以上跑存在问题，想问一下您的具体pytorch配置
另外想问一下现在版本和您最早发出的版本有何区别
谢谢

**Comment by wangg12** [comment]
新版本主要是用了lite让多gpu更丝滑，我之前的经验是pytorch 1.8.x有问题，1.9+没有问题。
