### ISSUE TITLE
are lm_imgn, lm_renders_blender and VOCdevkit required for training on LM ?

### ISSUE THREAD

**Issue by trabelsimahdi** [THU-DA-6D-Pose-Group/GDR-Net#84]
Hi everyone,
I am a novice here. I want to know if the other data are required for training on LM.
Also, if anyone can guide me through making it work on my own data, I would be very grateful.

**Comment by wangg12** [comment]
Different settings require different datasets, you can check the configs for details.

Check https://github.com/THU-DA-6D-Pose-Group/GDR-Net/discussions/62 for how to work on your own data.
