### ISSUE TITLE
BOP evaluation's results don't match paper's results on LM-O

### ISSUE THREAD

**Issue by LudovicoGranata** [THU-DA-6D-Pose-Group/GDR-Net#88]
Hello, 
I followed the evaluation instruction
`./core/gdrn_modeling/test_gdrn.sh configs/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e.py 0 output/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e/gdrn_lmo_real_pbr.pth`
using the checkpoint that is provided in this repository. The results that I get evaluating with the [BOP toolkit](https://github.com/thodan/bop_toolkit.git) are the following:
{
  "bop19_average_recall": 0.6371949250288351,
  "bop19_average_recall_mspd": 0.80719723183391,
  "bop19_average_recall_mssd": 0.6251903114186852,
  "bop19_average_recall_vsd": 0.47919723183391005,
  "bop19_average_time_per_image": 0.060607782814723316
} 
while in the paper the results that are reported are the following
![Immagine 2022-08-17 130238](https://user-images.githubusercontent.com/18251575/185103224-9a02eb1e-5c21-49f9-863b-f2bf0e5e1c35.png)
could it be that the checkpoint provided in this repository is different from the one used in the paper?

**Comment by wangg12** [comment]
Yes. And lm bop uses a different test subset. its training images are also different. You can refer to bop challenge website for further info.

**Comment by LudovicoGranata** [comment]
thank you. It is possible to make available the checkpoint trained on the BOP training set?

**Comment by wangg12** [comment]
It is not trivial to share that model. As mentioned in readme, for training on bop, we did a refactor on the code, which is incompatible with code provided here. But I think it should be easy to train on bop by yourself. Similar training configs can be referred to https://github.com/THU-DA-6D-Pose-Group/self6dpp/tree/main/configs%2Fgdrn%2FlmoPbrSO. (this is another refactored version)

**Comment by LudovicoGranata** [comment]
Thank you very much for the help.
