### ISSUE TITLE
关于xyz_crop的作用的问题以及数据相关问题

### ISSUE THREAD

**Issue by pre60448** [THU-DA-6D-Pose-Group/GDR-Net#89]
您好，能否解答一下两个问题
1、xyz_crop的具体作用
2、不使用虚拟数据集会有很大影响吗
期待您的解答，谢谢

**Comment by wangg12** [comment]
1 物体三维坐标的标签
2 具体多大影响看你真实数据情况，你可以自己做实验比较下
