### ISSUE TITLE
One drive link seems not working

### ISSUE THREAD

**Issue by AlbertoRemus** [THU-DA-6D-Pose-Group/GDR-Net#90]
Hi, unfortunately  the One-Drive link of pretrained model seems to provide the following error on different browsers, do you have any insight about this?

Thanks in advance,

Alberto

![Screenshot from 2022-09-08 18-15-36](https://user-images.githubusercontent.com/54797872/189173245-290e3957-170b-41be-ae27-c7073459a38f.png)

**Comment by wangg12** [comment]
Sorry, I have no idea.

**Comment by AlbertoRemus** [comment]
May you provide it in another way? I can send you a mail to an empty drive where you can upload the content of the `gdrn` folder if you still have a local copy

**Comment by wangg12** [comment]
Sorry, I don't have the local copy any more. Maybe you can find some Chinese friends to help you download them from Baidu Netdisk.

**Comment by LudovicoGranata** [comment]
@AlbertoRemus  For me signing in OneDrive solved the problem

**Comment by AlbertoRemus** [comment]
> @AlbertoRemus For me signing in OneDrive solved the problem

@LudovicoGranata, it worked for me, many thanks!
