### ISSUE TITLE
请教论文中的一个问题？

### ISSUE THREAD

**Issue by sdu-huanhq** [THU-DA-6D-Pose-Group/GDR-Net#91]
王老师您好：
在论文中有这么一段话：it is well-known that all representations with four or fewer dimensions for 3D rotation have discontinuities in the Euclidean space
请问为什么使用旋转向量或四元数表示旋转会有不连续问题？

**Comment by wangg12** [comment]
参见引文：
Zhou et al., On the Continuity of Rotation Representations in Neural Networks. CVPR 2019.
