### ISSUE TITLE
OneDrive access

### ISSUE THREAD

**Issue by hoenigpeter** [THU-DA-6D-Pose-Group/GDR-Net#92]
Hi, I would like to try out your software, unfortunately I cannot access the necessary files from your OneDrive links: 

https://1drv.ms/u/s!Ah83ZdJvIaBnnjqVy9Eyn0yxDb8i?e=0Q3qRU
https://1drv.ms/u/s!Ah83ZdJvIaBnoEz5BM4Ho6_W_UUA?e=pj7Y7i

Used the correct password, but cannot connect to the cloud.

Help is appreciated!

**Comment by wangg12** [comment]
Maybe you can refer to https://github.com/THU-DA-6D-Pose-Group/GDR-Net/issues/90

**Comment by supriya-gdptl** [comment]
Hi @wangg12 ,

I am not able to access the OneDrive links. I followed the suggestion in #90, I logged-in to OneDrive account to download but I got following error:
![image](https://user-images.githubusercontent.com/27888233/205405405-e9431876-f8d4-4d04-b580-cb71a2151a15.png)

Could you please upload the files again?

Thank you,
Supriya

**Comment by wangg12** [comment]
Sorry, I forgot the login detials of onedrive. I think there are some options:

a: try using the BaiduNetdisk link for downloading the files (maybe you need to ask a Chinese friend for help)

b: try gdrnpp which has the onedrive files available

c: maybe someone else who downloaded the files succeessfully could share them

**Comment by supriya-gdptl** [comment]
Thank you @wangg12 for suggestions.
I was able to download using OneDrive.
I logged in to OneDrive account. Then, instead of downloading folders (which gave error), I went to individual files inside each folder and downloaded them.
