### ISSUE TITLE
Ambiguities for Symmetric Objects

### ISSUE THREAD

**Issue by pyni** [THU-DA-6D-Pose-Group/GDR-Net#94]
Hi.
After reading your codes. I have question about the ambiguities for symmetric objects.

It seems that the symmetry is only applied in Patch-P𝑛P network. But for Dense Correspondences Maps and Surface Region Attention Maps, they are regressed directly using equation (8) (L1 loss and CE loss). According to paper [1], this setting cannot handle symmetric objects since it penalizes pixels that have larger distances in the 3D space without any knowledge of the symmetry. It seems they should be:

![image](https://user-images.githubusercontent.com/18031767/205486942-baebc85b-ec12-447f-b2c9-cff1c89279a9.png)
(Equation(2) in paper[1])

So why they(M_SRA and M_2D-3D) can implicitly represent the symmetry of an object in your paper? Thanks.

[1]Park K, Patten T, Vincze M. Pix2pose: Pixel-wise coordinate regression of objects for 6d pose estimation[C]//Proceedings of the IEEE/CVF International Conference on Computer Vision. 2019: 7668-7677.

**Comment by wangg12** [comment]
Hi, because after optimization of CE loss, if the M_SRA has multiple peaks with similar probability, it is very likely there are some some ambiguities in the surface. This intuition is from the EPOS paper. You can also try the method in Pix2Pose for explicitly handling symmetry.

**Comment by pyni** [comment]
OK. Thanks for replying. I understand for M_SRA. 
But for M_2D-3D, maybe this problem still exists. Am I right?

**Comment by wangg12** [comment]
yes.
