### ISSUE TITLE
Generating test_bboxes/faster_R50_FPN_AugCosyAAE_HalfAnchor_lmo_pbr_lmo_fuse_real_all_8e_test_480x640.json file

### ISSUE THREAD

**Issue by supriya-gdptl** [THU-DA-6D-Pose-Group/GDR-Net#95]
Hello @wangg12,

Sorry to bother you again.

Could you please tell me how to generate `faster_R50_FPN_AugCosyAAE_HalfAnchor_lmo_pbr_lmo_fuse_real_all_8e_test_480x640.json` in `lmo/test/test_bboxes` folder?

Which code did you run to obtain this file?

Thank you,
Supriya

**Comment by wangg12** [comment]
I think you can refer to https://github.com/LZGMatrix/BOP19_CDPN_2019ICCV/tree/bop2020/detection/tools, but you might need to figure out the exact procedures yourself.

Another reference: https://github.com/THU-DA-6D-Pose-Group/self6dpp/tree/main/det/yolov4/tools
