### ISSUE TITLE
请教数据集中pose的定义

### ISSUE THREAD

**Issue by george66s** [THU-DA-6D-Pose-Group/GDR-Net#96]
王博您好，

感谢你们的精彩项目。关于数据集中物体的pose，有几个问题：

[{"cam_R_m2c": [0.0963063, 0.99404401, 0.0510079, 0.57332098, -0.0135081, -0.81922001, -0.81365103, 0.10814, -0.57120699], "cam_t_m2c": [-105.3577515, -117.52119142, 1014.8770132], "obj_id": 1}]

这里的m2c是指物体在相机坐标系的pose吗？还是指相机在世界坐标系里的6D位姿？

另外，在data_loader.py 中，计算了一个 allo_pose = egocentric_to_allocentric(pose)。这个新获得的allo_pose，是物体相对哪个坐标系的pose呢？

非常感谢！
George

**Comment by wangg12** [comment]
m2c 表示model to camera, 就是模型在相机坐标系的pose。

allo_pose是一个在不同平移下视角不变的表示，可以参见3d-rcnn: Instance-level 3d object reconstruction via render-and-compare. CVPR'18, 以及 CPS++: Improving Class-level 6D Pose and Shape Estimation From Monocular Images With Self-Supervised Learning. arXiv'20.

**Comment by george66s** [comment]
非常感谢。抱歉没有仔细看论文（文献24）。

George
