### ISSUE TITLE
lm config file

### ISSUE THREAD

**Issue by saintrealchoi** [THU-DA-6D-Pose-Group/GDR-Net#97]
First of all, thank you for your Awesome paper.

I want to train lm dataset + pbr for reproducing your paper's score ( ADD mean 56.1)
So, I modified config file in your github `configs/gdrn/lm/a6_cPnP)lm13.py` but, I cant get a similar result to your papers'

Can I get a config file for lm(real+pbr)?

Sincerely,

**Comment by wangg12** [comment]
It's lmo, not lm.
