### ISSUE TITLE
Visualization of predictions 

### ISSUE THREAD

**Issue by shreyesss** [THU-DA-6D-Pose-Group/GDR-Net#98]
Great work with the paper and code for GDR-Net . I was successful in replicating the results in the paper , but I couldn't find a way to visualize the predictions and ground truth pose . Please direct us to the code used for visualizing the results (LMO dataset) as shown in the supplementary material . Thanks !

**Comment by wangg12** [comment]
It should be easy to get the visualizations. The basic idea is to render the objects on the gray original image. The contours can be obtained from rendered masks.
